version: "3"

services:
  gaaserver:
    image: geoseg-server:latest
    container_name: gaa-server
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    build:
      context: "."
      dockerfile: Dockerfile2
    # command: python serverside.py --source-data-dir=/app/METEOSAT-data/MSG/ --data-type=METEOSAT-MCS --port=1999 --no-cnn
    # command: python serverside.py --source-data-dir=/data --data-type=METEOSAT-MCS --port=1999 --no-cnn
    # command: bash
    command: python serverside.py --source-data-dir=/data --data-type=METEOSAT-MCS --port=1999 --no-cnn
    restart: always
    environment:
      RABBITMQ_HOSTNAME: ${RABBITMQ_HOSTNAME}
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      ASSIGNING_TASKS_RABBITMQ_QUEUE_NAME: ${ASSIGNING_TASKS_RABBITMQ_QUEUE_NAME}
      TASKS_REPORTS_RABBITMQ_QUEUE_NAME: ${TASKS_REPORTS_RABBITMQ_QUEUE_NAME}
      MINIO_HOSTNAME: ${MINIO_HOSTNAME:-minio}
      MINIO_PORT: ${MINIO_PORT:-9000}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_BUCKET_NAME: ${MINIO_BUCKET_NAME}
    networks:
      - backend
      - frontend
    ports:
      - "127.0.0.1:1999:1999"
      - "127.0.0.1:2222:2224"
    volumes:
      - ./:/code
      - /mnt/data/METEOSAT-data/MSG:/data
    working_dir: /code


  mongo:
    image: mongo:5.0.30 # 5.0.30 is the latest 5.x version at the time of writing. Using 5.x due to compatibility issues with current Docker service version at the station
    container_name: mongo
    restart: always
    ports:
      - 0.0.0.0:${MONGODB_PORT:-27017}:${MONGODB_PORT:-27017}
    volumes:
      - ${MONGODB_PATH:-./mongodb}:/data/db
    networks:
      - backend


  # rabbitmq:
  #   image: rabbitmq:3-management
  #   container_name: gaa-rabbitmq
  #   restart: always
  #   ports:
  #     - 5672:5672
  #     - 15672:15672
  #   environment:
  #     RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME:-rabbitmq_username}
  #     RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD:-rabbitmq_password}
  #   networks:
  #     - gaa-back-tier
  #     - gaa-front-tier


  # minio:
  #   image: minio/minio:latest
  #   container_name: gaa-minio
  #   restart: always
  #   volumes:
  #     - minio_data:/data
  #   ports:
  #     - 9000:9000
  #     - 9001:9001
  #   command: server --address ":9000" --console-address ":9001" /data
  #   environment:
  #     MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY:-minio}
  #     MINIO_SECRET_KEY: ${MINIO_SECRET_KEY:-minio123}
  #     MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minio}
  #     MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minio123}
  #   networks:
  #     - gaa-back-tier
  #     - gaa-front-tier
  

  


# volumes:
#   minio_data:
  
networks:
  backend:
    name: gaa-back-tier
  frontend:
    driver: bridge
    name: gaa-front-tier